name: Deploy to Hosting
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload files via SSH (password)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "./*"
          target: "/xanderwhite_ru/public_html"
          strip_components: 1  # Удаляет лишние вложенные папки при копировании
